### ISSUE TITLE
Doesn't work with CachedStaticFilesStorage

### ISSUE THREAD

**Issue by yuchant** [timmyomahony/django-pagedown#25]
When I enable `CachedStaticFileStorage` I get the following error:

ValueError: The file 'admin/css/pagedown.css' could not be found with <django.contrib.staticfiles.storage.CachedStaticFilesStorage object at 0x110410c50>.

Disable it and I'm fine.

**Comment by eillarra** [comment]
Same here, but with `whitenoise.django.GzipManifestStaticFilesStorage` (it fails with `CachedStaticFileStorage` too). Is there a way I can install the package as an standalone app and debug this?

```
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.paasprovider/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/app/.paasprovider/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/app/.paasprovider/python/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/app/.paasprovider/python/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/app/.paasprovider/python/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/app/.paasprovider/python/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/app/.paasprovider/python/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/app/.paasprovider/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/tmp/builddir/myproject/apps/core/admin.py", line 5, in <module>
    from pagedown.widgets import PagedownWidget
  File "/app/.paasprovider/python/lib/python2.7/site-packages/pagedown/widgets.py", line 56, in <module>
    class AdminPagedownWidget(PagedownWidget, admin_widgets.AdminTextareaWidget):
  File "/app/.paasprovider/python/lib/python2.7/site-packages/pagedown/widgets.py", line 57, in AdminPagedownWidget
    class Media:
  File "/app/.paasprovider/python/lib/python2.7/site-packages/pagedown/widgets.py", line 59, in Media
    'all': (compatible_staticpath('admin/css/pagedown.css'),)
  File "/app/.paasprovider/python/lib/python2.7/site-packages/pagedown/utils.py", line 12, in compatible_staticpath
    return staticfiles_storage.url(path)
  File "/app/.paasprovider/python/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "/app/.paasprovider/python/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "/app/.paasprovider/python/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'admin/css/pagedown.css' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x7ff0911fa990>
```

**Comment by eillarra** [comment]
It seems to me that one possible solution will be to use something like this to [load the files](https://github.com/timmyomahony/django-pagedown/blob/master/pagedown/utils.py#L9) in `utils.py` (not tested):

```python
try:
    # >= 1.4
    from django.templatetags.static import static
    return static(path)
except ImportError:
    pass
```

**Comment by eillarra** [comment]
I can confirm that this change makes it work: https://github.com/eillarra/django-pagedown/commit/c8a7b9acc6c66a44eeb9ceac91587bb8ad08ad89

@timmyomahony Can you test this? I don´t think this will cause any regression, and it will make it work with `CachedStaticFilesStorage`.

@yuchant Does this solve the issue for you too? You can load the package in you requirements file using:
```
-e git+https://github.com/eillarra/django-pagedown@c8a7b9acc6c66a44eeb9ceac91587bb8ad08ad89#egg=django_pagedown-master
```

**Comment by timmyomahony** [comment]
Hey Eneko, thank you very much for this. I will try it out as soon as possible and merge.

**Comment by timmyomahony** [comment]
I'm very late catching up with this. I've pulled in those changes which should fix the issue.

**Comment by yuchant** [comment]
:+1:
